global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "airflow-web"
    metrics_path: /health
    static_configs:
      - targets: ["airflow-webserver:8080"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
